### ISSUE TITLE
Experience.py raise expection in first message

### ISSUE THREAD

**Issue by nuclearMonkeys** [blongty/CazzuBot#15]
In line 67 of experience.py:
**bonus_exp = max(0, potential_bonus - potential_bonus *   ((count-1)/_EXP_DECAY_UNTIL_BASE)^_EXP_DECAY_FACTOR)**

A type error is raised due to the following:
**TypeError: '>' not supported between instances of 'complex' and 'int'**

This is because of the count-1 in bonus_exp. The second value returns the following:
**(28-0.01565247584249853j)**

**Comment by blongty** [comment]
This was fixed a while back with somewhere on commit [8b64e74](https://github.com/blongty/CazzuBot/commit/8b64e74f42b57ae94b53423ed6d85c1cf389c0bd). iirc the issue was that instead of ^ we need to use **.
